### ISSUE TITLE
Trying to install your theme, but got error instead

### ISSUE THREAD

**Issue by simonitfi** [senthilnathang/odoo_backend_theme#2]
![image](https://user-images.githubusercontent.com/23297584/35676601-0793f998-0755-11e8-81c8-f9d256b4f527.png)

```
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 333, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//*[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `webclient_bootstrap`
[view_id: 1928, xml_id: n/a, model: n/a, parent_id: 170]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo/odoo-server/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//*[@id=\'oe_main_menu_navbar\']">\' cannot be located in parent view\n\nError context:\nView `webclient_bootstrap`\n[view_id: 1928, xml_id: n/a, model: n/a, parent_id: 170]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 719, in _tag_template
    return self._tag_record(record, data_node)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo/odoo-server/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/odoo/odoo-server/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//*[@id='oe_main_menu_navbar']">' cannot be located in parent view

Error context:
View `webclient_bootstrap`
[view_id: 1928, xml_id: n/a, model: n/a, parent_id: 170]
None" while parsing None:3, near
<data inherit_id="web.webclient_bootstrap">
        <xpath expr="//t[@t-set='head']" position="inside">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        </xpath>

        <xpath expr="//*[@id='oe_main_menu_navbar']" position="replace">
            <nav class="navbar-default navbar-static-side" role="navigation">
                <div class="logo-area">
                    <img t-attf-src="/theme_extensia/static/src/img/logo.png" class="logo"/>
                    <img t-attf-src="/theme_extensia/static/src/img/logo_mini.png" class="logo_mini"/>
                </div>
                <div class="sidebar-collapse" id="oe_main_menu_placeholder">
                    <t t-call="web.menu"/>
                </div>
            </nav>
        </xpath>

        <xpath expr="//div[@class='o_main']" position="replace">
            <div id="page-wrapper" class="gray-bg">
                <div class="row border-bottom">
                    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                        <div class="navbar-header">
                            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"/> </a>
                        </div>
                        <ul class="nav navbar-top-links navbar-right oe_user_menu_placeholder oe_systray"/>
                    </nav>
                </div>
<!--
                <div class="openerp openerp_webclient_container oe_webclient">
                    <div class="oe_application"/>
                </div>
-->
				<div class="o_main_content"/>
                <div class="footer">
                    <div class="pull-right"><strong>Extensia</strong></div>
                    <div><strong>Copyright</strong> © 2017</div>
                </div>
            </div>
        </xpath>
    </data>
```

**Comment by senthilnathang** [comment]
@simosuu  which version of odoo ?

**Comment by simonitfi** [comment]
Sorry I did not mention that. Odoo CE 11 From github 25.1.

**Comment by senthilnathang** [comment]
Looks like the version you are using has been update with code in web/views/web_templates.xml 
oe_main_menu_navbar?

https://github.com/odoo/odoo/blob/11.0/addons/web/views/webclient_templates.xml#L630

**Comment by SalahAdDin** [comment]
@senthilnathang This is my version:
`Odoo 11.0-20180122 (Community Edition)`

**Comment by SalahAdDin** [comment]
I saw this problem happens when you install this theme in a already installed app database and with a old different theme.
I tried to install it in a clean database, i have no problems.

**Comment by senthilnathang** [comment]
no activity
