### ISSUE TITLE
Error after uninstallation

### ISSUE THREAD

**Issue by satriani-vai** [senthilnathang/odoo_backend_theme#4]
Odoo backend don't works after uninstallaion

```
odoo.addons.base.ir.ir_qweb.qweb.QWebException
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/user/PycharmProjects/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_menu_secondary_36220
TypeError: 'NoneType' object is not subscriptable

Error to render compiling AST
TypeError: 'NoneType' object is not subscriptable
Template: web.menu_secondary
Path: /templates/t/ul/t
Node: <t t-foreach="menu['children']" t-as="menu">
                <li>
                    <t t-if="menu['children']">
                        <a>
                            <t t-esc="menu['name']"/>
                            <span class="fa arrow"/>
                        </a>
                    </t>
                    <t t-if="not menu['children']">
                        <t t-call="web.menu_link"/>
                    </t>
                    <t t-call="web.menu_secondary_submenu"/>
                </li>
            </t>
```

**Comment by brain4d** [comment]
I got the same error after uninstallation.

**Comment by teddiey** [comment]
Got the same error, but restored a new database, solved the issue. Always backup your DB before installing modules.

**Comment by SalahAdDin** [comment]
Same, actually with installation too:
```
Error:
Uncaught TypeError: Cannot read property 'type' of null

http://localhost:8069/web/content/647-cf4ee12/web.assets_backend.js:498
Traceback:
TypeError: Cannot read property 'type' of null
    at Class.do_load_state (http://localhost:8069/web/content/647-cf4ee12/web.assets_backend.js:498:56)
    at http://localhost:8069/web/content/647-cf4ee12/web.assets_backend.js:436:132
    at http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:802:681
    at fire (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:796:299)
    at Object.add [as done] (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:797:467)
    at Array.<anonymous> (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:802:649)
    at Function.each (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:625:767)
    at Object.<anonymous> (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:802:560)
    at Function.Deferred (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:803:194)
    at Object.then (http://localhost:8069/web/content/505-aadf65c/web.assets_common.js:802:525)
```

**Comment by Zegorax** [comment]
Hello,
Why is this closed ? I have the same error after uninstall
